### ISSUE TITLE
Add "unknown" status?

### ISSUE THREAD

**Issue by bricas** [checkitonus/php-cachet-api#13]
Hi, I was just testing out this toolkit and the first component that I had created in the web interface returned an error via the library:

`PHP Warning:  constant(): Couldn't find constant CheckItOnUs\Cachet\Component::UNKNOWN`

Unknown is ID 0, so perhaps that should be addded?

Cheers.

**Comment by awjudd** [comment]
Sorry for the delay @bricas I can add this in now

**Comment by awjudd** [comment]
This should be added in with version 1.0.12

**Comment by bricas** [comment]
Thanks!
